### ISSUE TITLE
Using purefa_ds role with 5.3.15 and ansible 2.9 fails

### ISSUE THREAD

**Issue by amlucent** [Pure-Storage-Ansible/FlashArray-Collection#251]
Using purefa_ds role with 5.2.0+ and ansible 2.9 fails to create a ds entry.  Omitting group_base parameter as instructed causes failure msg: "parameters are required together: uri, bind_password, bind_user, base_dn, group_base".  Adding group_base parameter will cause a failure "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made.  Adding certificate verification is strongly advised".  

I would expect the latter to fail as the documentation is clear this is an unsupported parameter with 5.2.0+ but running without it seems to require it.

**To Reproduce**
run the following on a 5.3.15 FlasharrayX90 with RHEL8 ansible 2.9.25, python 3.6.8:

```
- name: Delete existing directory service
  purefa_ds:
    state: absent
    fa_url: 10.10.10.2
    api_token: e31060a7-21fc-e277-6240-25983c6c4592

- name: Create directory service (disabled) - 5.2.0 or higher  #this is where the failure occurs
  purefa_ds:
    uri: "ldap://lab.purestorage.com"
    base_dn: "DC=lab,DC=purestorage,DC=com"
    bind_user: Administrator
    bind_password: password
    fa_url: 10.10.10.2
    api_token: e31060a7-21fc-e277-6240-25983c6c4592

- name: Enable existing directory service
  purefa_ds:
    enable: true
    fa_url: 10.10.10.2
    api_token: e31060a7-21fc-e277-6240-25983c6c4592

```

**Additional context**
I am running at a dark site so I am unable to supply logs or additional information through this support channel.  I will reach out via pure support for a follow up.
