### ISSUE TITLE
Unable to create snapshot policy with multiple rules

### ISSUE THREAD

**Issue by MilesTails** [Pure-Storage-Ansible/FlashArray-Collection#266]
**Describe the bug**
Unable to create snapshot policy with multiple rules. Error claims that interval of the same policy must be in multiples . Confirmed that we are able to create the rule via the gui. I have reviewed the code and can't see this specific error message.

Also just on a side note to this, how do I map snapshot policies to directories? I had a look through the code and docs but I couldn't work out or see anywhere how to make that mapping?

**To Reproduce**
Data Model:
```yaml
fa_snapshot_policies:
  - name: "test-snapshot-pol"
    rules:
      - snap_client_name: "foo"
        snap_suffix: "miles"
        snap_every: 1440
        snap_keep_for: 1440
      - snap_client_name: "foo2"
        snap_suffix: "miles2"
        snap_every: 900
        snap_keep_for: 900
```

Ansible task:
```yaml
- name: Create snapshot policies
  purestorage.flasharray.purefa_policy:
    name: "{{item.0.name}}"
    policy: snapshot
    snap_client_name: "{{item.1.snap_client_name | mandatory}}"
    snap_suffix: "{{item.1.snap_suffix | default(omit)}}"
    snap_every: "{{item.1.snap_every | mandatory }}"
    snap_keep_for: "{{item.1.snap_keep_for | mandatory}}"
    snap_at: "{{item.1.snap_at | default(omit)}}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ fa_token }}"
  loop: "{{ fa_snapshot_policies | subelements('rules') }}"    
```

On run receive error: 
`Failed to create new rule for Snapshot policy test-snapshot-pol. Error: Snapshot interval of the rules in the same policy must be multiples`

**Expected behavior**
It creates the second rule.

**Environment**
Ansible 2.10.2
Collection v1.12.1+policy monkey patch
Purity//FA - 6.1.10
