### ISSUE TITLE
Insecure Request Purefa_info

### ISSUE THREAD

**Issue by RomainDusi** [Pure-Storage-Ansible/FlashArray-Collection#274]
**Describe the bug**
Hello,

While trying to do a purefa_info to gather informations, i got the following error :
[Purefa_info_error.txt](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/8424841/Purefa_info_error.txt)
Note that it appends on the purefa_info bloc but not on the purefa_host or purefa_hg.

Thank you.

**To Reproduce**
Python 3.6.8
Purestorage 1.19.0
Py-Pure-Client 1.22.0
Netaddr 0.9.0
Requests 2.25.1
Urllib3 1.26.5

Storage bay uses a self signed certificate
Purity//FA 6.1.11

Output of "https://<array_mgmt_vip>/api/api_version" :
{"version": ["1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11", "1.12", "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8"]}

```
- name: Collecter infos baie Pure Storage
  purefa_info:
    gather_subset: 
    - all
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  register: array_info
  delegate_to: localhost
```
