### ISSUE TITLE
`state` parameter for `purefa_pg` module does not detect pgroups in trash

### ISSUE THREAD

**Issue by sirhc-chris** [Pure-Storage-Ansible/FlashArray-Collection#300]
**Describe the bug**
the `state` parameter for `purefa_pg` module does not detect if the protection group is in the trash so does not perform a change if `state: present`

**To Reproduce**

```
- name: Configure protection group
  purestorage.flasharray.purefa_pg:
    pgroup: "{{ pgroup_name }}"
    enabled: true
    hostgroup: "{{ hostgroup_name }}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ fa_token }}"
    state: present
```
Delete the protection group (no eradication, just destroy to trash) then re-run the task configuring the protection group

ansible will report no change as the pgroup exists but it lacks awareness of it being in trash:
```
TASK [pure_flasharray : Configure protection group] ***********
ok: [localhost] => {"changed": false}
```

**Expected behavior**
If a protection group is in the trash and `state: present` then the protection group should be `recovered`
