### ISSUE TITLE
`target` parameter for `purefa_pg` module is ignored for an existing pgroup

### ISSUE THREAD

**Issue by sirhc-chris** [Pure-Storage-Ansible/FlashArray-Collection#301]
**Describe the bug**
If a protection group already exists then the `target` parameter on the `purefa_pg` module is set, no change is made

**To Reproduce**

Create a protection group:
```
- name: Configure protection group
  purestorage.flasharray.purefa_pg:
    pgroup: "{{ pgroup_name }}"
    enabled: true
    hostgroup: "{{ hostgroup_name }}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ fa_token }}"
    state: present
```
Then add a target:
```
- name: Configure protection group
  purestorage.flasharray.purefa_pg:
    pgroup: "{{ pgroup_name }}"
    enabled: true
    hostgroup: "{{ hostgroup_name }}"
    target: "{{ target_name }}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ fa_token }}"
    state: present
```

ansible will report a change but the target is not set on the pgroup
```
TASK [pure_flasharray : Configure protection group] ***********
changed: [localhost] => {"changed": true}
```

I have only tested with an offload target, not an array target

**Expected behavior**
Adding the `target` parameter updates an existing protection group
