### ISSUE TITLE
`purefa_pg` module should not issue a failure if a pgroup already exists on an offload target

### ISSUE THREAD

**Issue by sirhc-chris** [Pure-Storage-Ansible/FlashArray-Collection#305]
**Describe the bug**
If a protection group is configured with an offload target the first run succeeds (when the protection group is created on the offload target), but subsequent runs to update the protection group fail

**To Reproduce**

Configure a protection group with an offload target:
```
- name: Configure protection group
  purestorage.flasharray.purefa_pg:
    pgroup: "{{ pgroup_name }}"
    enabled: true
    hostgroup: "{{ hostgroup_name }}"
    target: "{{ target_name }}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ fa_token }}"
    state: present
```
Observe the successful creation of the protection group on the offload target:
```
changed: [localhost] => {"changed": true}
```

Rerun the play and observe the failure as the protection group already exists on the offload target:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Protection Group test-pg already exists on offload target s3."}
```

**Expected behavior**
The `purefa_pg` module should be idempotent, a protection group which already exists on the offload target should not be considered a failure condition. When the `update_pgroup` function is called and the protection group already exists on the offload target processing should continue
