### ISSUE TITLE
"API version does not support setting SafeMode on a protection group."

### ISSUE THREAD

**Issue by samuellay** [Pure-Storage-Ansible/FlashArray-Collection#329]
**Module purefa_pg Failes when "safe_mode" Var is Set**
At:

https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/master/plugins/modules/purefa_pg.py#L89 

we see:

  ```
safe_mode:
    description:
    - Enables SafeMode restrictions on the protection group
    - B(Once set disabling this can only be performed by Pure Technical Support)
    type: bool
    default: False
    version_added: '1.13.0
```
	
My target array is running Purity/FA 6.1.13

https://support.purestorage.com/FlashArray/PurityFA/Purity_FA_REST_API/FlashArray_REST_API_Reference_Guides

says that API 1.13 was shipped with Purity 5.0

The playbook, _pure_pg.yml:

```
---
- name: Manage Pure protection group (pg)
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  hosts: "{{ array_name }}"
  connection: local
  collections:
    - purestorage.flasharray
  gather_facts: no
  roles:
    - role: pure_pg
```
	

The role: roles/pure_pg/tasks/main.yml

```
---
- name: Set name variable to <pod_name>::<pg_name>
  ansible.builtin.set_fact:
    pgroup: "{{ pod_name }}::{{ pg_name }}"
  when: pod_name is defined and pod_name != ""

- name: Set name variable to <pg_name>  [ No Pod ]
  ansible.builtin.set_fact:
    pgroup: "{{ pg_name }}"
  when: pod_name is undefined or pod_name == ""

- name: Manage Pure protection group
  purestorage.flasharray.purefa_pg:
    pgroup: "{{ pgroup }}"
    #target: "{{ offload_target | default(omit)) }}"
    enabled: "{{ enabled }}"
    state: "{{ pg_state }}"
    eradicate: "{{ eradicate }}"
    safe_mode: "{{ enable_safe_mode }}"
    fa_url: "{{ ip }}"
    api_token: "{{ api_token }}"
```
	

The parameter file: pure_pg_param.yml

	

```
array_name: syn14p01st001
pod_name: bobspod
pg_name: bobspg
enabled: yes
pg_state: present
enable_safe_mode: yes
eradicate: no
```
Run the playbook:
```
ansible-playbook -a '@pure_pg_params.yml' _pure_pg.yml
```
The inventory containing IP and API token vault are specified in ansible.cfg

	
When executing this playbook, I get the following error message:
```
"API version does not support setting SafeMode on a protection group."
```
The playbook runs as expected if the safe_mode line is commented out.

I think it should work since the API shipped with 6.1.13 should be in 
the 2.x range.  Or am I mis-interpreting something?
