### ISSUE TITLE
bug in purefa_certs.py 

### ISSUE THREAD

**Issue by pda79** [Pure-Storage-Ansible/FlashArray-Collection#425]
Error when using module purefa_certs

**To Reproduce**
use the module  with state: sign

```
purestorage.flasharray.purefa_certs:
    state: sign
    export_file: files/csr
    key_size: 2048
```

**Expected behavior**
working csr request

![2023-07-20 11_32_14-PWVD1410 - Poste de DEV Windows - Desktop Viewer](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/assets/25984812/84ef0389-5778-44ed-ae4e-86b6b8a940c5)

Additional context
Ansible Pure Collection 1.20.0

python module version:
purestorage                        1.19.0
py-pure-client                     1.33.1
