### ISSUE TITLE
Deprecation warning reported while installing Pure collection

### ISSUE THREAD

**Issue by colinet** [Pure-Storage-Ansible/FlashArray-Collection#540]
**Describe the bug**
While installing Pure Ansible collection, a warning is displayed.

```
TASK [ds-profile-control_machine : Install Pure Flasharray collection from Galaxy based on hostvars] ***************************************************
Friday 26 January 2024  11:17:13 +0100 (0:00:00.058)       0:01:49.384 ********
[DEPRECATION WARNING]: The DependencyMixin is being deprecated. Modules should use community.general.plugins.module_utils.deps instead. This feature
will be removed from community.general in version 9.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [xxxxxxxxxxxxxxxx] 
```

**To Reproduce**
Run below playbook:

```
- name: Install Pure Flasharray collection from Galaxy based on hostvars
  community.general.ansible_galaxy_install:
    type: collection
    name: purestorage.flasharray:{{ acm_custom_collection_version_pure }}
    force: true
  become: true
  become_method: ansible.builtin.su
  become_user: "{{ acm_owner }}"
  when:
    - hostvars[machine].acm_custom_collection_version_pure is defined
  tags: custom_collection_pure
```

**Expected behavior**
No warning should be exposed.

**Desktop (please complete the following information):**
- OS : RHEL 9.2
- Ansible

```
[aaaaaaaaa@xxxxxxxxxxxx~]$  ansible --version
ansible [core 2.15.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxxxxxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/xxxxxxxxxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.16 (main, May 29 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
[aaaaaaaaa@xxxxxxxxxxxx ~]$  
```

```
[aaaaaaaaa@xxxxxxxxxxxx ~]$  ansible-galaxy collection list |grep -i flash
purestorage.flasharray        1.24.0 
purestorage.flasharray        1.18.0 
[aaaaaaaaa@xxxxxxxxxxxx ~]$
```
