### ISSUE TITLE
Error while changing interface

### ISSUE THREAD

**Issue by Natscho2001** [Pure-Storage-Ansible/FlashArray-Collection#563]
**Describe the bug**
I try to configure an interface but run into an error:

```bash
failed: [linpure18 -> localhost] (item={'name': 'ct0.eth2', 'address': '0.0.0.0/0', 'gateway': '0.0.0.0'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "address": "0.0.0.0/0",
        "gateway": "0.0.0.0",
        "name": "ct0.eth2"
    },
  .....
Traceback (most recent call last):
  File \"/home/.../.ansible/tmp/ansible-tmp-1714461797.5878756-3999730-101050925160799/AnsiballZ_purefa_network.py\", line 107, in <module>
    _ansiballz_main()
  File \"/home/.../.ansible/tmp/ansible-tmp-1714461797.5878756-3999730-101050925160799/AnsiballZ_purefa_network.py\", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/.../.ansible/tmp/ansible-tmp-1714461797.5878756-3999730-101050925160799/AnsiballZ_purefa_network.py\", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_network', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_network', _modlib_path=modlib_path),
  File \"<frozen runpy>\", line 226, in run_module
  File \"<frozen runpy>\", line 98, in _run_module_code
  File \"<frozen runpy>\", line 88, in _run_code
  File \"/tmp/ansible_purestorage.flasharray.purefa_network_payload_66vridq6/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py\", line 769, in <module>
  File \"/tmp/ansible_purestorage.flasharray.purefa_network_payload_66vridq6/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py\", line 739, in main
  File \"/tmp/ansible_purestorage.flasharray.purefa_network_payload_66vridq6/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py\", line 342, in update_interface
  File \"/home/.../.local/lib/python3.11/site-packages/netaddr/strategy/ipv4.py\", line 99, in valid_str
    raise TypeError('Invalid type: %s' % type(addr))
TypeError: Invalid type: <class 'NoneType'>
",
    "module_stdout": "",
    "msg": "MODULE FAILURE
See stdout/stderr for the exact error",
    "rc": 1
```

**To Reproduce**

Create a task:
```yaml
- name: FlashArray > array_basic> Set array replication
  purestorage.flasharray.purefa_network:
    name: "{{ item.name }}"
    address: "{{ item.address | string }}"
    gateway: "{{ item.gateway | string }}"
    servicelist: "replication"
    mtu: "1500"
    state: present
    fa_url: "{{ inventory_hostname }}.domain.local"
    api_token: "{{ api_token_obj.result.Content }}"
  loop: "{{ replication | default([]) }}"
```

Add vars to inventory:
```yaml
          replication:
            - name: "ct0.eth2"
              address: "0.0.0.0/0"
              gateway: "0.0.0.0"
            - name: "ct1.eth2"
              address: "0.0.0.0/0"
              gateway: "0.0.0.0"
```

Run the playbook 

```bash
ansible-playbook playbook.yml -i inventories --check -vvv
```

Reference for task from the docs

```yaml
 - name: Remove an IP address from iSCSI interface ct0.eth4
  purestorage.flasharray.purefa_network:
    name: ct0.eth4
    address: 0.0.0.0/0
    gateway: 0.0.0.0
    fa_url: 10.10.10.2
    api_token: c6033033-fe69-2515-a9e8-966bb7fe4b40
```

**Expected behavior**

The given interface should be configured with the IP. In this case, it should delete an existing IP configuration.

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux 8.9
 - Version 

```bash
ansible-playbook [core 2.15.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/.../.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.5 (main, Sep 22 2023, 15:34:29) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```
