### ISSUE TITLE
purefa_policy doesn't update existing snapshot policies

### ISSUE THREAD

**Issue by dbuenoparedes** [Pure-Storage-Ansible/FlashArray-Collection#568]
**Describe the bug**
When creating new snapshot policies the module works fine, it creates it with the specified settings. Although when updating an existing policy's values it doesn't do anything, seems that it doesn't check current frequency nor retention (every / keep_for) values and just checks if the policy exists with the given name.

**To Reproduce**
1. Create a snapshot policy, example:
```
- name: Define snapshot policies
  purestorage.flasharray.purefa_policy:
    name: "snap-daily"
    policy: snapshot
    snap_client_name: "daily"
    snap_every: 1440
    snap_keep_for: 10080
    fa_url: "{{ fa_url }}"
    api_token: "{{ api_token }}"
```
2. Change the value of `snap_keep_for` from 10080 to 20160 (1 week to 2 weeks), run the same task, I get the following output:
```
TASK [purestorage : Define snapshot policies] **********************************************************************************************************************************************************************************
Tuesday 21 May 2024  16:37:40 -0400 (0:00:00.527)       0:00:10.686 *********** 
ok: [us1pure01] => (item={'name': 'snap-daily', 'frequency': 1440, 'retention': 20160, 'client_name': 'daily'})
```
3. The policy doesn't change the retention time. The only way to force this is to delete the policy and then run the task to re-create it with the correct/updated values.

**Expected behavior**
Scheduled policy module should update existing schedule policy's configuration.

**Desktop (please complete the following information):**
 - OS: Ubuntu Mate 22.04
 - Ansible version: ansible [core 2.16.7]
 - Purestorage.flasharray collection version: 1.28.0

**Additional context**
I haven't tried changing other values nor other policies (like quota), not sure if they could also be affected by this.
