### ISSUE TITLE
directory services roles modifications fail

### ISSUE THREAD

**Issue by tylergmuir** [Pure-Storage-Ansible/FlashArray-Collection#598]
**Describe the bug**
There are multiple directory services roles modifications that result in an error stating:
  AttributeError: 'Client' object has no attribute 'get_directory_service_roles'

**To Reproduce**
1. Run the below ansible code to clear the DS role mapping (regardless of there is one or not):
```
    - name: Remove LDAP role assignment
      purestorage.flasharray.purefa_dsrole:
        role: array_admin
        state: absent
```

**Expected behavior**
The DS role mapping should be removed if it exists or no changes should be made if it doesn't exist.

**Additional context**
In purefa_dsrole.py, there are multiple instances where the method being called is `array.get_directory_service_roles` but the correct method is `array.get_directory_services_roles`.
