### ISSUE TITLE
Unable to set readonly group

### ISSUE THREAD

**Issue by tdevos-ROSEN** [Pure-Storage-Ansible/FlashArray-Collection#607]
**Describe the bug**
While setting the readonly group I receive

```bash
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Client' object has no attribute 'post_directory_service_roles'. Did you mean: 'post_directory_services_roles'?
```

**To Reproduce**
```yaml
- name: FlashArray > array_basic> Create array_read directory service role
  purestorage.flasharray.purefa_dsrole:
    role: readonly
    group_base: "{{ ad.groupbase }}"
    group: "{{ ad.read }}"
    fa_url: "{{ inventory_hostname }}"
    api_token: "{{ api_token_obj.result.Content }}"
  tags: array
  delegate_to: localhost
```

**Expected behavior**
Set the group, it is working for:

```yaml
- name: FlashArray > array_basic> Create array_admin directory service role
  purestorage.flasharray.purefa_dsrole:
    role: array_admin
    group_base: "{{ ad.groupbase }}"
    group: "{{ ad.array_admin }}"
    fa_url: "{{ inventory_hostname }}"
    api_token: "{{ api_token_obj.result.Content }}"
  tags: array
  delegate_to: localhost
```

```bash
TASK [pure_management : FlashArray > array_basic> Create array_admin directory service role] **********************************************************************************************
ok: [linpure18 -> localhost]

TASK [pure_management : FlashArray > array_basic> Create array_read directory service role] ***********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Client' object has no attribute 'post_directory_service_roles'. Did you mean: 'post_directory_services_roles'?
```

**Additional context**
```bash
ansible [core 2.16.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/PATH/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/PATH/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Jun 19 2024, 10:06:03) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True

Collection             Version
---------------------- -------
ansible.posix          1.5.4
community.general      9.2.0
community.mysql        3.7.2
community.okd          2.3.0
community.vmware       3.7.0
cyberark.pas           1.0.27
kubernetes.core        2.4.0
purestorage.flasharray 1.30.2
purestorage.flashblade 1.18.0
```
