### ISSUE TITLE
Errors moving volumes out of volume group using purefa_volume module

### ISSUE THREAD

**Issue by calebdonald** [Pure-Storage-Ansible/FlashArray-Collection#611]
**Describe the bug**
Using the purefa_volume module, I'm getting errors trying to move a volume out of volume group to the local array. It appears that the volume gets moved, but the playbook reports errors and fails out.

**To Reproduce**
```
- name: Move provided volumes out of volume group
    purestorage.flasharray.purefa_volume:
      name: "vg-RH-test2/i-RH-test2_02"
      move: local
      fa_url: "{{ fa_url }}"
      api_token: "{{ api_token }}"
      disable_warnings: true
    ignore_errors: true
```

**Expected behavior**
Volume should be moved out of the volume group and into the local array. Module should report the change. Instead the volume is moved, but the module fails.

**Screenshots**
![pure_move_vol_fail](https://github.com/user-attachments/assets/9d4471d0-dc50-4f69-809b-095543b138e0)

**Additional context**
![collection_details](https://github.com/user-attachments/assets/abbadbec-eea3-4051-a979-eaa7dfee267c)
![ansible_version](https://github.com/user-attachments/assets/e5a1511d-b8f1-4f65-bc0f-a2b58b99236d)
