### ISSUE TITLE
purefa_dsrole fails with This module requires Purity//FA 6.6.3

### ISSUE THREAD

**Issue by tdevos-ROSEN** [Pure-Storage-Ansible/FlashArray-Collection#623]
**Describe the bug**
The array is running on 6.6.6, and the module throws the error anyway.

**To Reproduce**

Run a task like

```yaml
  purestorage.flasharray.purefa_dsrole:
    role: storage_admin
    group_base: "{{ ad.groupbase }}"
    group: "{{ ad.storage_admin }}"
    fa_url: "{{ inventory_hostname }}"
    api_token: "{{ api_token_obj.result.Content }}"
```

The result is

```yaml
fatal: [linpure28 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "disable_warnings": false,
            "fa_url": "ARRAY_URL",
            "group": "OU_TO_GROUP",
            "group_base": "GROUP_BASE",
            "role": "array_admin",
            "state": "present"
        }
    },
    "msg": "This module requires Purity//FA 6.6.3 and higher. For older Purity versions please use the ``purefa_dsrole_old`` module"
```

**Expected behavior**

The task should set a storage_admin group. I chhecked the code and MIN_DSROLE_API_VERSION = "2.30" is set, If I check the api version of the array https://ARRAY_URL/api/api_version) i get:

```json
{
    "version": [
        "1.0",
        "1.1",
        "1.2",
        "1.3",
        "1.4",
        "1.5",
        "1.6",
        "1.7",
        "1.8",
        "1.9",
        "1.10",
        "1.11",
        "1.12",
        "1.13",
        "1.14",
        "1.15",
        "1.16",
        "1.17",
        "1.18",
        "1.19",
        "2.0",
        "2.1",
        "2.2",
        "2.3",
        "2.4",
        "2.5",
        "2.6",
        "2.7",
        "2.8",
        "2.9",
        "2.10",
        "2.11",
        "2.13",
        "2.14",
        "2.15",
        "2.16",
        "2.17",
        "2.19",
        "2.20",
        "2.21",
        "2.22",
        "2.23",
        "2.24",
        "2.25",
        "2.26",
        "2.27",
        "2.28",
        "2.29",
        "2.30",
        "2.31",
        "2.32"
    ]
}
```
