### ISSUE TITLE
purefa_network fails to create a file vif interface with lacp bonds as subinterfaces

### ISSUE THREAD

**Issue by dbuenoparedes** [Pure-Storage-Ansible/FlashArray-Collection#646]
**Describe the bug**
When trying to create a file vif interface using lacp0 and lacp1 as subinterfaces it fails with the message:
- `msg: Child subinterface lacp0 does not exist`

When I try the same task using the CLI it works as expected, command used:
- `purenetwork eth create vif --address 10.10.10.10/24 --subinterfacelist lacp0,lacp1 filevif`

**To Reproduce**
1. Create 2 lacp bond interfaces
2. Create file vif interface with `purefa_network` using one or both lacp bond interfaces previously created as subinterfaces
3. See error

**Expected behavior**
File vif interface should be created the same way as with the CLI command.

**Screenshots**
This is the output of the task, I'm looping through all the interfaces and creating them with the same task:
```
TASK [purestorage : Configure network interfaces for NFS] **********************************************************************************************************************************************************
ok: [purenfs01-dc6] => (item={'name': 'lacp0', 'type': 'lacp', 'enabled': True, 'subordinates': ['ct0.eth10', 'ct0.eth11'], 'mtu': 9000})
ok: [purenfs01-dc6] => (item={'name': 'lacp1', 'type': 'lacp', 'enabled': True, 'subordinates': ['ct1.eth10', 'ct1.eth11'], 'mtu': 9000})
failed: [purenfs01-dc6] (item={'name': 'filevif', 'type': 'vif', 'enabled': True, 'address': '10.10.10.10/24', 'gateway': '10.10.10.1', 'servicelist': 'file', 'subinterfaces': ['lacp0', 'lacp1'], 'mtu': 1500}) => changed=false 
  ansible_loop_var: net
  msg: Child subinterface lacp0 does not exist
  net:
    address: 10.10.10.10/24
    enabled: true
    gateway: 10.10.10.1 1500
    name: filevif
    servicelist: file
    subinterfaces:
    - lacp0
    - lacp1
    type: vif
```

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04
 - ansible core 2.16.7
 - purestorage.flasharray 1.31.0/1.31.1 (both fail the same way)
 - Pure flasharray model FA-X20R3, version 6.3.17

**Additional context**
Task definition I'm using:
```
- name: Configure network interfaces for NFS
  purestorage.flasharray.purefa_network:
    name: "{{ net.name }}"
    interface: "{{ net.type }}"
    enabled: "{{ net.enabled }}"
    mtu: "{{ net.mtu }}"
    address: "{{ net.address | default(omit) }}"
    gateway: "{{ net.gateway | default(omit) }}"
    subordinates: "{{ net.subordinates | default([]) }}"
    servicelist: "{{ net.servicelist | default([]) }}"
    subinterfaces: "{{ net.subinterfaces | default([]) }}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ api_token }}"
  loop: "{{ fs.networks }}"
  loop_control:
    loop_var: net
  when: fs.networks is defined
  tags: configure-file-network
```
Network variables:
```
  networks:
    - name: lacp0
      type: lacp
      enabled: true
      subordinates:
        - ct0.eth10
        - ct0.eth11
      mtu: 9000
    - name: lacp1
      type: lacp
      enabled: true
      subordinates:
        - ct1.eth10
        - ct1.eth11
      mtu: 9000
    - name: filevif
      type: vif
      enabled: true
      address: "10.10.10.10/24"
      gateway: "10.10.10.1"
      servicelist: file
      subinterfaces:
        - lacp0
        - lacp1
      mtu: 1500
```
