### ISSUE TITLE
Any way that i could update the quota limit size in directory quota policy?

### ISSUE THREAD

**Issue by ohideyuki** [Pure-Storage-Ansible/FlashArray-Collection#717]
In my case, we need extend the size of quota limit of one filesystem at PureFA.
I try this playbook, but it looks like create a new rule with new quota_limit and get the alert msg "Only one enforced rule can be defined per policy"
`````
- hosts: localhost
  tasks:
    - name: extend quota_limit of one directory quota policy
      purestorage.flasharray.purefa_policy:
        name: sam_quota_policy
        policy: quota
        directory: "sam:root"
        quota_limit: 30G
        fa_url: man01pure01.inf.webex.com
        api_token: 
`````
<img width="1444" alt="Image" src="https://github.com/user-attachments/assets/e44fd7a9-32a6-4b59-98bd-80d63bfdd581" />
