### ISSUE TITLE
Adding volume to SafeMode PG: API version does not support setting SafeMode on a protection group

### ISSUE THREAD

**Issue by lukeroberts** [Pure-Storage-Ansible/FlashArray-Collection#726]
**Describe the bug**
When running an ansible role that attempts to add a volume to a Protection Group that has SafeMode enabled, it errors out with ```API version does not support setting SafeMode on a protection group```

**To Reproduce**
```
- name: Add Backup volume to SafeMode protection group
  purestorage.flasharray.purefa_pg:
    name: "{{ sm_pg_name }}"
    enabled: true
    safe_mode: true
    fa_url: "{{ pure_array_name }}.{{domain_name}}"
    api_token: "{{ pure_arrays[pure_array_name].api_token }}"
    volume:
      - "{{ backup_volume_info.volume_name }}"
    state: present
  delegate_to: localhost
````
Output:
```
fatal: [REDACTED -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "context": "",
            "disable_warnings": false,
            "enabled": true,
            "eradicate": false,
            "fa_url": "REDACTED",
            "host": null,
            "hostgroup": null,
            "name": "REDACTED",
            "rename": null,
            "safe_mode": true,
            "state": "present",
            "target": null,
            "volume": [
                "vvol-REDACTED-8024fb0f-vg/Data-8562fab9"
            ]
        }
    },
    "msg": "API version does not support setting SafeMode on a protection group."
}
```

**Expected behavior**
Volume gets added to PG

**Additional context**
We are on Purity v6.7.1, but around the time that this broke we recently applied the ```security_patch_fa_2025_A``` patch to our fleet. It reports as the following version and I am wondering if ansible is using logic to check the purity version to see if SafeMode is supported like in this issue: #329 

<img width="669" alt="Image" src="https://github.com/user-attachments/assets/14663821-0726-41c8-9cf3-13eb94193901" />
