### ISSUE TITLE
add volume to multiple protection groups on creation

### ISSUE THREAD

**Issue by chtourou-youssef** [Pure-Storage-Ansible/FlashArray-Collection#730]
Hello
I've this task , that create a volume , and in my purestorage , i ve 4 protection group

```
  - name: Create VM Volume
    purefa_volume:
      name: "{{ vm_volume }}"
      size: "{{ size }}"
      with_default_protection: false
      fa_url: "{{fa_url}}"
      api_token: "{{fa_api_token}}"
      add_to_pgs: "{{ item }}"
    loop:
      - "{{ pgdaily }}"
      - "{{ pgmonthly }}"
      - "{{ pgweek }}"
      - "{{ pgrestore }}"

```
however, that the first one is taken and marked as changed, the others are OK but it does not add it in.
