### ISSUE TITLE
purestorage.flasharray.purefa_smtp incorrectly configuring relay_host

### ISSUE THREAD

**Issue by scotttyso** [Pure-Storage-Ansible/FlashArray-Collection#761]
**Describe the bug**

**To Reproduce**
https://docs.ansible.com/ansible/latest/collections/purestorage/flasharray/purefa_smtp_module.html#ansible-collections-purestorage-flasharray-purefa-smtp-module

```
  - name: Settings > System > Alerts and Notifications > Alert Routing | for {{ array_fqdn }}
    purestorage.flasharray.purefa_smtp:
      api_token: "{{ api_token }}"
      disable_warnings: true
      fa_url: "{{ array_url }}"
      relay_host: "{{ system.alerts_and_notifications.alert_routing.relay_host }}"
      sender_domain: "{{ system.alerts_and_notifications.alert_routing.sender_domain }}"
    when: system.alerts_and_notifications is defined and system.alerts_and_notifications.alert_routing is defined

```

When running the playbook I see the following

```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "body_prefix": null,
            "disable_warnings": true,
            "encryption_mode": "starttls",
            "fa_url": "r143b-pure03.rich.ciscolabs.com",
            "password": null,
            "relay_host": "smtp-ext.cisco.com",
            "sender": null,
            "sender_domain": "rich.ciscolabs.com",
            "state": "present",
            "subject_prefix": null,
            "user": null
        }
    }
}
```

But when I login to the Array the sender_domain is configured for both the relay_host and the sender_domain

**Expected behavior**

relay_host attribute should be applied to the relay_host configuration field.

**Screenshots**

I am running the latest version of the module

```
ansible [core 2.17.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tyscott@rich.ciscolabs.com/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/tyscott@rich.ciscolabs.com/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, May 27 2025, 17:12:29) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
# /home/tyscott@rich.ciscolabs.com/.ansible/collections/ansible_collections
---------------------------------------- -------
purestorage.flasharray                   1.34.1 
purestorage.flashblade                   1.20.0 
# /usr/lib/python3/dist-packages/ansible_collections
---------------------------------------- -------
purestorage.flasharray                   1.32.0 
purestorage.flashblade                   1.19.1 
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
