### ISSUE TITLE
purestorage.flasharray.purefa_user character error when using Ansible loops

### ISSUE THREAD

**Issue by jvergatiCW** [Pure-Storage-Ansible/FlashArray-Collection#771]
**Describe the bug**
I'm attempting to use the [purestorage.flasharray.purefa_user](https://docs.ansible.com/ansible/latest/collections/purestorage/flasharray/purefa_user_module.html#ansible-collections-purestorage-flasharray-purefa-user-module) module to create multiple new local user accounts across my FA fleet in an automated manner. Upon building the playbook and adding an Ansible loop to iterate through a simple list of account names defined in a variable to create multiple accounts in a single playbook run, I get the error message below.

```
failed: [localhost] (item=test-admin1) => {"ansible_loop_var": "item", "changed": false, "item": "test-admin1", "msg": "name must contain a minimum of 1 and a maximum of 32 characters (alphanumeric or `-`). All letters must be lowercase."}
failed: [localhost] (item=test-admin2) => {"ansible_loop_var": "item", "changed": false, "item": "test-admin2", "msg": "name must contain a minimum of 1 and a maximum of 32 characters (alphanumeric or `-`). All letters must be lowercase."}
```

When I run the playbook without the loop to add a single account (test-admin1), it works fine. This also works fine when added manually via the Purity GUI, and I'm not able to add any account with any name I've tried that should meet the character requirements in the error when the loop is used, so this does not really seem to be an issue with characters.

**To Reproduce**

main.yml Playbook task code
```
---
- name: Create local user accounts on FlashArray.
  purestorage.flasharray.purefa_user:
    fa_url: "{{ flasharray_fqdn }}"
    api_token: "{{ api_token }}"
    name: "{{ user_account_name }}"
    password: "{{ user_password }}"
    role: "{{ user_role }}"
    state: present
    disable_warnings: true
  loop: "{{ user_account_name }}"
  delegate_to: localhost
```
vars.yml vars file
```
---
flasharray_fqdn: flasharray.domain.local
user_account_name: ['test-admin1', 'test-admin2']
user_role: array_admin
```
Ansible version information
```
ansible [core 2.17.5]
  config file = None
  configured module search path = ['/Users/user.account/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/miniconda3/envs/ansible-env01/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/user.account/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/miniconda3/envs/ansible-env01/bin/ansible
  python version = 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:22:19) [Clang 14.0.6 ] (/opt/miniconda3/envs/ansible-env01/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

**Expected behavior**
Ansible will iterate through the list defined in variable `user_account_name` to create a new local user account for each item defined in the list on the specified FlashArray. 

**Desktop (please complete the following information):**
 - OS: MacOS 15.5
